#Makefile, compiles everything into a runnable executable called redAttack.
all: redAttack main.o redCounter.o

redAttack: main.o redCounter.o
	clang++ -Wall -lpng main.o -o redAttack

main.o: main.cpp
	clang++ -Wall -c -std=c++17 main.cpp redCounter.o

redCounter.o: redCounter.cpp
	clang++ -Wall -c -std=c++17 redCounter.cpp

# Clean rule
clean:
	rm -f redCounter.o main.o pokemon
